# Generated by Django 4.2.11 on 2024-04-13 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='都道府県')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='送料')),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_costs', to='accounts.prefecture')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='prefecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.prefecture'),
        ),
    ]
