# Generated by Django 4.2.11 on 2024-04-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_prefecture_shippingcost_user_prefecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingcost',
            name='cost',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='送料'),
        ),
    ]
