# Generated by Django 4.2.11 on 2024-04-13 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_shippingcost_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prefecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.prefecture', verbose_name='都道府県'),
        ),
    ]
