# Generated by Django 4.2.11 on 2024-04-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_prefecture_shipping_cost_delete_shippingcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='住所'),
        ),
    ]
