# Generated by Django 4.2.11 on 2024-03-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maruko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apparel',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='apparel_images'),
        ),
    ]
