# Generated by Django 4.2.11 on 2024-04-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maruko', '0005_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentText',
            fields=[
                ('text_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
