# Generated by Django 4.2.11 on 2024-04-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maruko', '0009_alter_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
    ]
