# Generated by Django 4.2.11 on 2024-04-13 01:30

from django.db import migrations, models
import maruko.models


class Migration(migrations.Migration):

    dependencies = [
        ('maruko', '0010_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=maruko.models.slug_maker, max_length=20),
        ),
    ]
