# Generated by Django 4.2.11 on 2024-04-13 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maruko', '0012_product_prefecture_shipping_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prefecture_shipping_cost',
        ),
    ]
